# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Owen Williams
email: owen@char.gd
description: > # this means to ignore newlines until "baseurl:"
  Owen is a freelance developer, UX writer, maker and technologist based in Amsterdam, Netherlands. He's always looking for great new projects!
url: "https://owenwillia.ms"
baseurl: "/" # the subpath of your site, e.g. /blog
twitter:
  username: ow
social:
    links:
      - https://twitter.com/ow
      - https://github.com/ow
      - https://instagram.com/findingnewo
logo: /images/card.png
twitter_username: ow
github_username:  ow
telegram: https://t.me/owenwil
instagram: https://instagram.com/findingnewo
location: Amsterdam, Netherlands

services:
  - title: UX Writing
    description: Let your interface speak. Brilliant copy stands out in a world where voice is an afterthought in the design process, letting your product shine. 
    icon: far fa-pencil
    color: blue
  - title: Content
    description: Get your product in front of the right people. I'll help you build content that readers love, and converts them into customers.
    icon: far fa-rocket
    color: green
  - title: Technical Product Marketing
    description: Developers can smell marketing a mile away. Get your tools in the hands of the right people, with authentic marketing that doesn't stink.
    icon: far fa-bullhorn
    color: purple

career:
  - title: Founder / Freelancer
    company: Charged
    description: I help brands with copy, strategy and more, as a for-hire resource. Working with a small group of companies closely to help them get the most of their resources, and grow products with great copy.
    icon: "/images/career/charged.jpg"
    color: charged
    dates: 2017 - Present
  - title: Digital Director
    company: VanMoof
    description: Built the engineering organization from the ground, moving app + web development in-house. Responsible for managing the engineering team, building out a digital strategy, and launching the brand into new countries online.
    icon: "/images/career/vanmoof.png"
    color: vanmoof
    dates: 2016 - 2017
  - title: Editor
    company: The Next Web
    description: Telling stories about the people behind technology, writing news and breaking down complex topics for wide audiences. Managed implementation of performance-focused overhaul of the site, slashing loading times 60 percent.
    icon: "/images/career/tnw.png"
    color: tnw
    dates: 2013 - 2016
  - title: Head of marketing / growth 
    company: Hoist
    description: Developing marketing strategy and executing it autonomously, reaching out to developers and coding our marketing site. Use wide range of analytics tools (Mixpanel, Crazyegg, Google Analytics) to iterate in real-time on strategy.
    icon: "/images/career/hoist.png"
    color: hoist
    dates: 2013 - 2014
  - title: Infrastructure/Devops Engineer
    company: Xero
    description: Engineer on critical infrastructure team responsible for scaling the platform to millions of users. Supported product team to debug issues on the platform, optimized performance and built out a deployment pipeline for high availability.
    icon: "/images/career/xero.png"
    color: xero
    dates: 2011 - 2013

projects: 
  - title: Hubble
    description: Custom-engineered platform for building your community, and getting paid for your work.
    color: hubble
    action: Join waitlist
    emoji: ðŸ“¡
    url: https://producthunt.co/upcoming/hubble
  - title: re:Charged
    description: Paid morning technology briefing and community, without clickbait or advertising.
    color: charged
    action: Subscribe now
    emoji: âš¡
    url: https://producthunt.co/upcoming/hubble
  - title: Call Me Maybe
    description: Phone calls are disruptive and archaic. Screen your calls, get a SMS with the reason to talk.
    color: call-me-maybe
    action: Join waitlist
    emoji: ðŸ“±
    url: https://callmemaybe.app
  - title: Podcast
    description: A tech podcast with a difference. Three hosts, casual conversations about the state of the industry.
    color: podcast
    action: Listen now 
    emoji: ðŸŽ¤
    url: https://char.gd/podcast

collections:
  work:
    output: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
