# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Owen Williams
email: owen@char.gd
description: > # this means to ignore newlines until "baseurl:"
  Owen Williams is trying to make tech friendlier with words at Shopify in Toronto, Canada. Come and say hello!
url: "https://owenwillia.ms"
baseurl: "/" # the subpath of your site, e.g. /blog
client_availability: false
twitter:
  username: ow
author:
  twitter: ow
  picture: /images/itme.jpg
social:
    name: Owen Williams
    links:
      - https://twitter.com/ow
      - https://github.com/ow
      - https://instagram.com/findingnewo
      - https://www.youtube.com/channel/UCZeXk3K3Ow8Peu_KnDjxjhQ
logo: /images/card.png
twitter_username: ow
github_username:  ow
telegram: https://t.me/owenwil
instagram: https://instagram.com/findingnewo
location: Toronto, Canada
services:
  - title: UX Writing
    description: Give your product a voice. UX Writing can help your users get more done, and make your product easier to use. 
    icon: far fa-pencil
    color: blue
  - title: Content
    description: Get your product in front of the right people. I'll help you build content that readers love and converts into customers.
    icon: far fa-rocket
    color: green
  - title: Product
    description: Building a design system, internal marketing or a new product? I've helped companies big and small with words and code to get it done.
    icon: far fa-laptop-code
    color: pink
  - title: Technical Product Marketing
    description: Developers can smell marketing a mile away. Get your tools in the hands of the right people, with authentic marketing that doesn't put them off.
    icon: far fa-bullhorn
    color: yellow

career:
  - title: Content Strategy Manager
    company: Shopify
    description: I lead a team of talented content strategists working on hairy developer platform problems at Shopify. We're a part of the UX discipline, and are working to build the best developer experience possible.
    icon: "images/career/shopify.png"
    color: shopify
    dates: 2019 - Present
  - title: Founder / Freelancer
    company: Charged
    description: I help brands with copy, strategy and more, as a for-hire resource. Working with a group of companies in every stage to help them get the most from their resources, and grow products with great copy.
    icon: "/images/career/charged.jpg"
    color: charged
    dates: 2017 - 2019
  - title: Digital Director
    company: VanMoof
    description: <p>Built the digital marketing organization from the ground up to focus on data-driven decision making and moved app + web development in-house.</p><p>I led the engineering team, built out a digital marketing + voice strategy, and helped launch the brand into new countries (including Japan) online.</p>
    icon: "/images/career/vanmoof.png"
    color: vanmoof
    dates: 2016 - 2017
  - title: Editor
    company: The Next Web
    description: Telling stories about the people behind technology, writing news and breaking down complex topics for wide audiences. Managed implementation of performance-focused overhaul of the site, slashing loading times 60 percent.
    icon: "/images/career/tnw.png"
    color: tnw
    dates: 2013 - 2016
  - title: Infrastructure/Devops Engineer
    company: Xero
    description: Engineer on critical infrastructure team responsible for scaling the platform to millions of users. Supported product team to debug issues on the platform, optimized performance and built out a deployment pipeline for high availability.
    icon: "/images/career/xero.png"
    color: xero
    dates: 2011 - 2013

projects: 
  - title: Hubble
    description: Custom-engineered platform for building your community, and getting paid for your work.
    color: hubble
    action: Join waitlist
    emoji: üì°
    url: https://producthunt.co/upcoming/hubble
  - title: re:Charged
    description: Paid morning technology briefing and community, without clickbait or advertising.
    color: charged
    action: Subscribe now
    emoji: ‚ö°
    url: https://char.gd/recharged
  - title: Write Together
    description: Learn to write through the power of habit-building. It's a social platform that encourages writing anything.
    color: call-me-maybe
    action: Try it now
    emoji: üìù
    url: https://writetogether.space
  - title: Podcast
    description: A tech podcast with a difference. Three hosts, casual conversations about the state of the industry.
    color: podcast
    action: Listen now 
    emoji: üé§
    url: https://char.gd/podcast

nav:
- title: About 
  url: about

- title: Now 
  url: now

- title: Blog
  url: blog

- title: Services
  url: services

- title: My work
  url: work

- title: Contact
  url: contact

collections:
  work:
    output: false
  now:
    permalink: /now/:path/
    output: true

autopages:
  collections:
      layouts: 
        - 'now.html'
      title: 'Posts in Now :coll' # :coll is replaced by the collection name
      permalink: '/collection/:coll'
      
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
